export const leagues: { [key: string]: string } = {
  "32": new URL(
    "/src/assets/leagues/CUP-BLUE-Photoroom.png-Photoroom.png",
    import.meta.url,
  ).href,
  "34": new URL("/src/assets/leagues/Enterprise-Cup (1).png", import.meta.url)
    .href,
  "109": new URL("/src/assets/tournaments/Enterprise-Cup.png", import.meta.url)
    .href,
  "111": new URL("/src/assets/leagues/Rugby Super Series.png", import.meta.url)
    .href,
  "1": new URL("/src/assets/leagues/fkf-premier-league.png", import.meta.url)
    .href,
  "100": new URL("/src/assets/leagues/Kenya_Cup_logo.png", import.meta.url)
    .href,
  "196": new URL("/src/assets/tournaments/Kenya_Cup_logo.png", import.meta.url)
    .href,
  "90": new URL("/src/assets/leagues/Kenya_Cup_logo.png", import.meta.url).href,
  "83": new URL("/src/assets/tournaments/elgon.png", import.meta.url).href,
  "238": new URL("/src/assets/tournaments/sportpesa-colored.png", import.meta.url).href,
  // "83": new URL("/src/assets/tournaments/elgon.png", import.meta.url).href,
};

export const teamImages: { [key: string]: string } = {
  "166": new URL("/src/assets/rugby/blak blad.png", import.meta.url).href,
  "1044": new URL("/src/assets/rugby/Buffaloes.PNG", import.meta.url).href,
  "1046": new URL("/src/assets/rugby/Cheetahs.PNG", import.meta.url).href,
  "812": new URL("/src/assets/rugby/Dkfv4aSW0AAR1hB.png", import.meta.url).href,
  "416": new URL("/src/assets/rugby/Dkfv4aSW0AAR1hB.png", import.meta.url).href,
  "459": new URL("/src/assets/rugby/Dkfv4aSW0AAR1hB.png", import.meta.url).href,
  "171": new URL("/src/assets/rugby/Impala.png", import.meta.url).href,
  "618": new URL("/src/assets/rugby/Impala.png", import.meta.url).href,
  "800": new URL("/src/assets/rugby/Impala.png", import.meta.url).href,
  "603": new URL("/src/assets/rugby/Impala.png", import.meta.url).href,
  "881": new URL("/src/assets/rugby/JKUAT.png", import.meta.url).href,
  "824": new URL("/src/assets/rugby/JKUAT.png", import.meta.url).href,
  "620": new URL("/src/assets/rugby/JKUAT.png", import.meta.url).href,
  "578": new URL("/src/assets/rugby/JKUAT.png", import.meta.url).href,
  "832": new URL("/src/assets/rugby/kabras.png", import.meta.url).href,
  "797": new URL("/src/assets/rugby/kabras.png", import.meta.url).href,
  "462": new URL("/src/assets/rugby/kabras.png", import.meta.url).href,
  "243": new URL("/src/assets/rugby/kabras.png", import.meta.url).href,
  "469": new URL("/src/assets/rugby/KCB.png", import.meta.url).href,
  "172": new URL("/src/assets/rugby/KCB.png", import.meta.url).href,
  "1045": new URL("/src/assets/rugby/Lions.PNG", import.meta.url).href,
  "163": new URL("/src/assets/rugby/Meanmachinerfclogo.png", import.meta.url)
    .href,
  "626": new URL("/src/assets/rugby/Meanmachinerfclogo.png", import.meta.url)
    .href,
  "798": new URL("/src/assets/rugby/Meanmachinerfclogo.png", import.meta.url)
    .href,
  "458": new URL("/src/assets/rugby/Nondescripts.png", import.meta.url).href,
  "675": new URL("/src/assets/rugby/Nondescripts.png", import.meta.url).href,
  "616": new URL("/src/assets/rugby/Oilers.png", import.meta.url).href,
  "703": new URL("/src/assets/rugby/Oilers.png", import.meta.url).href,
  "869": new URL("/src/assets/rugby/Oilers.png", import.meta.url).href,
  "169": new URL("/src/assets/rugby/Oilers.png", import.meta.url).href,
  "702": new URL("/src/assets/rugby/Quins.png", import.meta.url).href,
  "613": new URL("/src/assets/rugby/Quins.png", import.meta.url).href,
  "605": new URL("/src/assets/rugby/Quins.png", import.meta.url).href,
  "471": new URL("/src/assets/rugby/Quins.png", import.meta.url).href,
  "1043": new URL("/src/assets/rugby/Rhinos.PNG", import.meta.url).href,
  "585": new URL("/src/assets/rugby/Rhinos.PNG", import.meta.url).href,
  "820": new URL("/src/assets/rugby/SC Pirates.png", import.meta.url).href,
  "819": new URL("/src/assets/rugby/trans-falcons.png", import.meta.url).href,
  "461": new URL("/src/assets/rugby/trans-falcons.png", import.meta.url).href,
  "162": new URL("/src/assets/rugby/trans-falcons.png", import.meta.url).href,
  "159": new URL("/src/assets/rugby/trans-falcons.png", import.meta.url).href,
  "899": new URL("/src/assets/rugby/Western Bulls (2).png", import.meta.url)
    .href,
  "466": new URL("/src/assets/rugby/Western Bulls (2).png", import.meta.url)
    .href,
  "979": new URL("/src/assets/football/Bondo United.png", import.meta.url).href,
  "612": new URL("/src/assets/football/Bungoma Queens.jpg", import.meta.url)
    .href,
  "1009": new URL("/src/assets/football/Bungoma Queens.jpg", import.meta.url)
    .href,
  "1035": new URL("/src/assets/football/COMPEL FC.png", import.meta.url).href,
  "183": new URL("/src/assets/football/Kayole Starlets.jpg", import.meta.url)
    .href,
  "494": new URL("/src/assets/football/KENYA PRISONS.png", import.meta.url)
    .href,
  "477": new URL(
    "/src/assets/football/Kibarage Sportiff (1).png",
    import.meta.url,
  ).href,
  "307": new URL(
    "/src/assets/football/Kings Football Academy.png",
    import.meta.url,
  ).href,
  "1141": new URL("/src/assets/football/KIRIGITI.png", import.meta.url).href,
  "291": new URL("/src/assets/football/KISPED.jpg", import.meta.url).href,
  "111": new URL("/src/assets/football/KSG.png", import.meta.url).href,
  "787": new URL("/src/assets/football/MAKARIOS.png", import.meta.url).href,
  "438": new URL("/src/assets/football/MathareUnited.png", import.meta.url)
    .href,
  "18": new URL("/src/assets/football/MathareUnited.png", import.meta.url).href,
  "1056": new URL(
    "/src/assets/football/Mombasa olympic Ladies.png",
    import.meta.url,
  ).href,
  "699": new URL("/src/assets/football/Mombasa Stars.jpg", import.meta.url)
    .href,
  "127": new URL("/src/assets/football/NAIROBI UNITED.png", import.meta.url)
    .href,
  "975": new URL("/src/assets/football/Nakuru Bucks.jpg", import.meta.url).href,
  "835": new URL("/src/assets/football/LSA.png", import.meta.url).href,
  "457": new URL("/src/assets/football/RE UNION.png", import.meta.url).href,
  "871": new URL("/src/assets/football/ROYAL SOCCER.png", import.meta.url).href,
  "487": new URL("/src/assets/football/ROYAL UNITED.png", import.meta.url).href,
  "287": new URL("/src/assets/football/SS ASSAD.png", import.meta.url).href,
  "55": new URL("/src/assets/football/TANDAZA.png", import.meta.url).href,
  "1029": new URL("/src/assets/football/Trans Nzoia FC.png", import.meta.url)
    .href,
  "545": new URL("/src/assets/football/UON OLYMPIC.png", import.meta.url).href,
  "839": new URL("/src/assets/rugby/kcb kobs.jpeg", import.meta.url).href,
  "880": new URL("/src/assets/football/VALEO.png", import.meta.url).href,
  "178": new URL("/src/assets/football/VIHIGA QUEENS (1).png", import.meta.url)
    .href,
  "58": new URL("/src/assets/football/VIONGOZI.png", import.meta.url).href,
  "805": new URL("/src/assets/football/WALALAH.png", import.meta.url).href,
  "174": new URL("/src/assets/football/WAYLIGHT.png", import.meta.url).href,
  "2": new URL("/src/assets/football/Gor-Mahia-logo (1).png", import.meta.url)
    .href,
  "77": new URL(
    "/src/assets/football/sofapaka-fc-logo-9B8F6A7B91-seeklogo.com.png",
    import.meta.url,
  ).href,
  "149": new URL(
    "/src/assets/football/Ulinzi_Stars_FC_logo.png",
    import.meta.url,
  ).href,
  "198": new URL(
    "/src/assets/football/Znoia_Sugar_F.C._logo-Photoroom.png-Photoroom.png",
    import.meta.url,
  ).href,
  "5": new URL(
    "/src/assets/football/tusker-fc-logo-2788AE204B-seeklogo.com.png",
    import.meta.url,
  ).href,
  "595": new URL("/src/assets/football/Shabana_FC_(logo).png", import.meta.url)
    .href,
  "6": new URL("/src/assets/football/kcb football logo.png", import.meta.url)
    .href,
  "36": new URL(
    "/src/assets/football/Kakamega_Homeboyz_F.C._logo.png",
    import.meta.url,
  ).href,
  "10": new URL("/src/assets/football/dIrN6fqG-bBiFBAKT.png", import.meta.url)
    .href,
  "1": new URL("/src/assets/football/Bidco_FC_logo.gif", import.meta.url).href,
  "147": new URL(
    "/src/assets/football/afc-leopards-logo-1FE51F62E5-seeklogo.com.png",
    import.meta.url,
  ).href,
  "76": new URL(
    "/src/assets/football/3633358601154909bfef9f231a6df682-0-1.png",
    import.meta.url,
  ).href,
  "84": new URL(
    "/src/assets/football/240982120_259204366207977_7073992088656259999_n-Photoroom.png-Photoroom.png",
    import.meta.url,
  ).href,
  "85": new URL("/src/assets/football/93869.png", import.meta.url).href,
  "7": new URL("/src/assets/football/61619.png", import.meta.url).href,
  "12": new URL("/src/assets/football/17104.png", import.meta.url).href,
  "557": new URL(
    "/src/assets/football/0078-Photoroom.png-Photoroom.png",
    import.meta.url,
  ).href,
  "533": new URL("/src/assets/rugby/Impala.png", import.meta.url).href,
  "532": new URL("/src/assets/rugby/Impala.png", import.meta.url).href,
  "465": new URL("/src/assets/rugby/Homeboyz.png", import.meta.url).href,
  "475": new URL("/src/assets/rugby/Catholic Monks Logo.png", import.meta.url)
    .href,
  "420": new URL("/src/assets/rugby/Nakuru RFC.png", import.meta.url).href,
  "464": new URL(
    "/src/assets/rugby/Kisumu_Rugby_Football_Club_Logo.jpg",
    import.meta.url,
  ).href,
  "408": new URL("/src/assets/rugby/Strathmore Leos.png", import.meta.url).href,
  "481": new URL("/src/assets/rugby/blak blad.png", import.meta.url).href,
  "474": new URL("/src/assets/rugby/Mwamba RFC.png", import.meta.url).href,
  "468": new URL("/src/assets/rugby/Oilers.png", import.meta.url).href,
  "558": new URL("/src/assets/rugby/UoE Trojans.png", import.meta.url).href,
  "472": new URL("/src/assets/rugby/Quins.png", import.meta.url).href,
  "762": new URL("/src/assets/rugby/Kabete Stallions.png", import.meta.url)
    .href,
  "1159": new URL("/src/assets/rugby/Kabete Stallions.png", import.meta.url)
    .href,
  "1257": new URL("/src/assets/rugby/Kabete Stallions.png", import.meta.url)
    .href,
  "112": new URL(
    "/src/assets/football/F.C._Talanta_logo-Photoroom.png-Photoroom.png",
    import.meta.url,
  ).href,
  "1648": new URL("/src/assets/uganda/Buffaloes.png", import.meta.url).href,
  "1919": new URL("/src/assets/rugby/buffaloes.jpeg", import.meta.url).href,
  "1646": new URL("/src/assets/rugby/buffaloes.jpeg", import.meta.url).href,
  "1653": new URL("/src/assets/uganda/Elgon Wolves 7s.png", import.meta.url)
    .href,
  "1656": new URL("/src/assets/uganda/Heathens 7s.png", import.meta.url).href,
  "844": new URL("/src/assets/uganda/Heathens 7s.png", import.meta.url).href,
  "1918": new URL("/src/assets/uganda/Heathens 7s.png", import.meta.url).href,
  "2037": new URL("/src/assets/uganda/Heathens 7s.png", import.meta.url).href,
  "1657": new URL("/src/assets/uganda/Hippos 7s.png", import.meta.url).href,
  "1655": new URL("/src/assets/uganda/Impis 7s.png", import.meta.url).href,
  "1652": new URL("/src/assets/uganda/Kobs.png", import.meta.url).href,
  "1651": new URL("/src/assets/uganda/Mongers.png", import.meta.url).href,
  "1660": new URL("/src/assets/uganda/Pirates Rugby.png", import.meta.url).href,
  "1661": new URL("/src/assets/uganda/Rams 7s.png", import.meta.url).href,
  "1647": new URL("/src/assets/uganda/Rhinos 7s.png", import.meta.url).href,
  "1688": new URL("/src/assets/uganda/Titans 7s.png", import.meta.url).href,
  "1715": new URL("/src/assets/uganda/Titans 7s.png", import.meta.url).href,
  "1659": new URL("/src/assets/uganda/Walukuba.png", import.meta.url).href,
  "1649": new URL("/src/assets/uganda/Warriors 7s.png", import.meta.url).href,
  "1713": new URL("/src/assets/uganda/Mustangs.png", import.meta.url).href,
  "1711": new URL("/src/assets/uganda/Silverbacks 7s.png", import.meta.url)
    .href,
  "1712": new URL("/src/assets/uganda/Buddu 7s.png", import.meta.url).href,
  "334": new URL("/src/assets/country/kenya.png", import.meta.url).href,
  "1803": new URL("/src/assets/country/uganda.png", import.meta.url).href,
  "1796": new URL("/src/assets/country/uganda.png", import.meta.url).href,
  "248": new URL("/src/assets/football/mara.jpeg", import.meta.url).href,
  "1745": new URL(
    "/src/assets/football/IMG-20250201-WA0002.jpg",
    import.meta.url,
  ).href,
  "72": new URL("/src/assets/football/IMG-20250201-WA0002.jpg", import.meta.url)
    .href,
  "1778": new URL(
    "/src/assets/football/IMG-20250201-WA0002.jpg",
    import.meta.url,
  ).href,
  "1879": new URL("/src/assets/football/Us Acli.jpeg", import.meta.url).href,
  "939": new URL("/src/assets/football/crown.jpeg", import.meta.url).href,
  "91": new URL("/src/assets/football/imara.png", import.meta.url).href,
  "1917": new URL("/src/assets/football/lifestyle.png", import.meta.url).href,
  "1929": new URL("/src/assets/football/pelicojam.png", import.meta.url).href,
  "1924": new URL("/src/assets/rugby/stanbic pirates.jpeg", import.meta.url)
    .href,
  "1937": new URL("/src/assets/football/impalaclub.png", import.meta.url).href,
  "1971": new URL("/src/assets/football/gardensportiff.png", import.meta.url)
    .href,
  "2063": new URL("/src/assets/football/ayala-athletic-fc.png", import.meta.url)
    .href,
  "2511": new URL("/src/assets/football/thika-vitambi.png", import.meta.url)
    .href,
  "2522": new URL("/src/assets/football/donholm-seniors.png", import.meta.url)
    .href,
  "2523": new URL("/src/assets/football/wazito.png", import.meta.url).href,
  "2524": new URL("/src/assets/football/panthers.png", import.meta.url).href,
  "2525": new URL("/src/assets/football/mamba.png", import.meta.url).href,
  "2526": new URL("/src/assets/football/leysa.png", import.meta.url).href,
  "2527": new URL("/src/assets/football/hippos.png", import.meta.url).href,
  "2528": new URL("/src/assets/football/maveto.png", import.meta.url).href,
  "2529": new URL("/src/assets/football/ndovus.png", import.meta.url).href,
  "2530": new URL("/src/assets/football/railway.png", import.meta.url).href,
  "2537": new URL(
    "/src/assets/football/kulundeng-original.png",
    import.meta.url,
  ).href,
  "2538": new URL("/src/assets/football/ulinzi-legends.png", import.meta.url)
    .href,
  "2544": new URL("/src/assets/country/china.png", import.meta.url).href,
  "2545": new URL("/src/assets/country/argentina.png", import.meta.url).href,
  "2543": new URL("/src/assets/country/spain.png", import.meta.url).href,
  "2546": new URL("/src/assets/country/brazil.png", import.meta.url).href,
  "2480": new URL("/src/assets/country/sa.png", import.meta.url).href,
  "2286": new URL("/src/assets/country/kenya.png", import.meta.url).href,
  "236": new URL("/src/assets/country/usa.png", import.meta.url).href,
  "241": new URL("/src/assets/country/uruguay.png", import.meta.url).href,
  "795": new URL("/src/assets/country/uruguay.png", import.meta.url).href,
  "2291": new URL("/src/assets/country/kenya.png", import.meta.url).href,
  "237": new URL("/src/assets/country/canada.png", import.meta.url).href,
  "1079": new URL("/src/assets/country/belgium.png", import.meta.url).href,
  "776": new URL("/src/assets/country/germany.png", import.meta.url).href,
  "1955": new URL("/src/assets/rugby/Quins.png", import.meta.url).href,
  "1948": new URL(
    "/src/assets/rugby/Kisumu_Rugby_Football_Club_Logo.jpg",
    import.meta.url,
  ).href,
  "1952": new URL("/src/assets/rugby/Nondescripts.png", import.meta.url).href,
  "1946": new URL("/src/assets/rugby/blak blad.png", import.meta.url).href,
  "1950": new URL("/src/assets/rugby/Impala.png", import.meta.url).href,
  "1954": new URL("/src/assets/rugby/Oilers.png", import.meta.url).href,
  "1949": new URL("/src/assets/rugby/Nakuru RFC.png", import.meta.url).href,
  "1957": new URL("/src/assets/rugby/Strathmore Leos.png", import.meta.url)
    .href,
  "1956": new URL("/src/assets/rugby/KCB.png", import.meta.url).href,
  "1947": new URL("/src/assets/rugby/kabras.png", import.meta.url).href,
  "2850": new URL("/src/assets/uganda/Rhinos 7s.png", import.meta.url).href,
  "1920": new URL("/src/assets/uganda/Warriors 7s.png", import.meta.url).href,
  "1921": new URL("/src/assets/uganda/sharks.jpeg", import.meta.url).href,
  "1645": new URL("/src/assets/uganda/impis.jpeg", import.meta.url).href,
  "2552": new URL("/src/assets/uganda/kakira.jpeg", import.meta.url).href,
  "1862": new URL("/src/assets/uganda/Walukuba.png", import.meta.url).href,
  "2828": new URL("/src/assets/uganda/mongers.jpeg", import.meta.url).href,
  "846": new URL("/src/assets/rugby/Mwamba RFC.png", import.meta.url).href,
  "1298": new URL("/src/assets/rugby/Quins.png", import.meta.url).href,
  "2853": new URL("/src/assets/uganda/storm.jpeg", import.meta.url).href,
  "2603": new URL("/src/assets/uganda/eagles.jpeg", import.meta.url).href,
  "2604": new URL("/src/assets/uganda/Rams 7s.png", import.meta.url).href,
  "1990": new URL("/src/assets/rugby/KCB.png", import.meta.url).href,
  "1951": new URL("/src/assets/rugby/Mwamba RFC.png", import.meta.url).href,
  "2092": new URL("/src/assets/rugby/alliance.jpeg", import.meta.url).href,
  "2857": new URL("/src/assets/rugby/kiambu.jpeg", import.meta.url).href,
  "933": new URL("/src/assets/rugby/lenana.jpeg", import.meta.url).href,
  "986": new URL("/src/assets/rugby/mangu.jpeg", import.meta.url).href,
  "1189": new URL("/src/assets/rugby/moi-forces.jpeg", import.meta.url).href,
  "930": new URL("/src/assets/rugby/nairobi-sch.jpeg", import.meta.url).href,
  "929": new URL("/src/assets/rugby/ofafa-jericho.jpeg", import.meta.url).href,
  "1198": new URL("/src/assets/rugby/strath-school.jpeg", import.meta.url).href,
  "2858": new URL("/src/assets/rugby/itangas.jpeg", import.meta.url).href,
  "2915": new URL("/src/assets/football/braeburn.jpeg", import.meta.url).href,
  "2916": new URL("/src/assets/football/braeside.jpeg", import.meta.url).href,
  "2920": new URL("/src/assets/football/brookhouse.jpeg", import.meta.url).href,
  "2918": new URL("/src/assets/football/crawford.jpeg", import.meta.url).href,
  "2129": new URL("/src/assets/football/hillcrest.jpeg", import.meta.url).href,
  "2148": new URL("/src/assets/football/nairobi-academy.jpeg", import.meta.url).href,
  "2123": new URL("/src/assets/football/peponi.jpeg", import.meta.url).href,
  "2917": new URL("/src/assets/football/premier.jpeg", import.meta.url).href,
  "2919": new URL("/src/assets/football/St Christopher.jpeg", import.meta.url).href,
  "2921": new URL("/src/assets/football/st-marys.jpeg", import.meta.url).href,
  "583": new URL("/src/assets/country/kenya.png", import.meta.url).href,
  "584": new URL("/src/assets/country/uganda.png", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
  // "": new URL("/", import.meta.url).href,
};
