import { Question, SurveySchema } from "@/lib/types/survey";

export const surveyQuestions: Question[] = [
  {
    id: 1,
    question: "Referral Code",
    type: "text",
    required: false,
    placeholder: "Leave blank if you didn't receive one",
    multiline: false,
  },
  {
    id: 2,
    question: "Gender",
    type: "choice",
    required: true,
    options: ["Male", "Female", "Other", "Prefer not to say"],
    multiple: false,
  },
  {
    id: 3,
    question: "Age bracket",
    type: "choice",
    required: true,
    options: ["Under 18", "18-24", "25-34", "35-44", "45-54", "55+"],
    multiple: false,
  },
  {
    id: 4,
    question: "Was ticket fairly priced?",
    type: "choice",
    required: true,
    options: ["Very fair", "Fair", "Neutral", "Unfair", "Very unfair"],
    multiple: false,
  },
  {
    id: 5,
    question: "Employment Status",
    type: "choice",
    required: true,
    options: ["Self-employed", "Employee", "Student", "Unemployed", "Retired"],
    multiple: false,
  },
  // New Question: How did you purchase your ticket?
  {
    id: 6,
    question: "How did you purchase your ticket?",
    type: "choice",
    required: true,
    options: [
      "Saved up to buy",
      "Paid cash when it was announced",
      "A friend/company bought for me",
      "Complimentary ticket",
    ],
    multiple: false,
    helpText: "Please select one option",
  },
  {
    id: 7,
    question: "How satisfied with vendors?",
    type: "choice",
    required: true,
    options: [
      "Very satisfied",
      "Satisfied",
      "Neutral",
      "Dissatisfied",
      "Very dissatisfied",
    ],
    multiple: false,
  },
  {
    id: 8,
    question: "How satisfied with entry process?",
    type: "choice",
    required: true,
    options: [
      "Very satisfied",
      "Satisfied",
      "Neutral",
      "Dissatisfied",
      "Very dissatisfied",
    ],
    multiple: false,
  },
  {
    id: 9,
    question: "Was it value for money?",
    type: "choice",
    required: true,
    options: [
      "Excellent value",
      "Good value",
      "Fair value",
      "Poor value",
      "Very poor value",
    ],
    multiple: false,
  },
  // New Question: Is it part of your Valentine treat?
  {
    id: 10,
    question:
      "Is this event part of your Valentine's treat for your better half?",
    type: "choice",
    required: true,
    options: ["Yes", "No"],
    multiple: false,
  },
  // New Question: How did you come to HSBC Event?
  {
    id: 11,
    question: "How did you travel to the HSBC Event?",
    type: "choice",
    required: true,
    options: [
      "Drove but had parking challenges",
      "Drove and found parking easily",
      "Came with public vehicle (matatu/bus)",
      "Hailed a cab (Uber/Bolt/Taxi)",
      "Walked",
      "Boda boda",
    ],
    multiple: false,
  },
  // New Question: Weekend engagement activities (Select 3)
  {
    id: 12,
    question: "What are your preferred weekend engagement activities?",
    type: "choice",
    required: true,
    options: [
      "Netflix and Chill",
      "Concert",
      "Sherehe (Party)",
      "Family time",
      "Rugby",
      "Local football",
      "EPL football",
      "Church/Religious activities",
      "Sports betting",
      "Gaming",
      "Shopping",
      "Eating out",
    ],
    multiple: true,
    maxSelections: 3,
    layout: "grid",
    helpText: "Please select up to 3 options",
  },
  {
    id: 13,
    question: "What can be done better?",
    type: "text",
    required: false,
    placeholder: "Please share your suggestions...",
    multiline: true,
  },
  {
    id: 14,
    question: "How did you get to know about the event?",
    type: "choice",
    required: true,
    options: [
      "Social media",
      "Friend/Family",
      "Email",
      "Website",
      "Radio",
      "TV",
      "Newspaper",
      "BillBoards",
      "Other",
    ],
    multiple: true,
    layout: "grid",
    other: true,
  },
  {
    id: 17,
    question: "Which rugby events have you attended in the last 1 year?",
    type: "choice",
    required: true,
    options: [
      "Safari 7s",
      "Kenya Cup Game",
      "Driftwood 7s",
      "Prinsloo 7s",
      "Embu 7s",
      "Dala 7s",
      "Christie 7s",
      "Kabeberi 7s",
      "International Test Match",
      "School/University",
      "Other",
      "None",
    ],
    multiple: true,
    other: true,
    layout: "grid",
  },
  {
    id: 18,
    question:
      "If you haven't attended any event, did HSBC meet your expectations?",
    type: "choice",
    required: false,
    options: [
      "Exceeded expectations",
      "Met expectations",
      "Below expectations",
      "N/A - I attended",
    ],
    multiple: false,
    conditional: {
      dependsOn: 15,
      condition: (answer: string) => answer === "0",
    },
  },
  {
    id: 19,
    question: "Do you want to be informed about future events?",
    type: "contact",
    required: false,
    fields: [
      {
        name: "phone",
        label: "Phone Number",
        type: "tel",
        placeholder: "+254 XXX XXX XXX",
      },
      {
        name: "email",
        label: "Email Address",
        type: "email",
        placeholder: "your@email.com",
      },
    ],
  },
  {
    id: 20,
    question: "Which KRU channels do you follow?",
    type: "choice",
    required: false,
    options: [
      "None",
      "Instagram",
      "WhatsApp",
      "Facebook",
      "TikTok",
      "X (Twitter)",
    ],
    multiple: true,
    layout: "grid",
  },
];

export const surveySchema: SurveySchema = {
  metadata: {
    title: "Kenya Rugby Union - HSBC Event Feedback Survey",
    description: "Help us improve future rugby events in Kenya",
    version: "1.0",
  },
  sections: [
    {
      id: "demographics",
      title: "Demographics",
      questions: [2, 3, 5],
    },
    {
      id: "ticket_purchase",
      title: "Ticket & Entry",
      questions: [4, 6, 8, 10],
    },
    {
      id: "event_experience",
      title: "Event Experience",
      questions: [7, 9, 11],
    },
    {
      id: "engagement",
      title: "Fan Engagement",
      questions: [12, 14, 17, 20],
    },
    {
      id: "feedback",
      title: "Feedback & Suggestions",
      questions: [13, 18],
    },

    {
      id: "contact",
      title: "Stay Connected",
      questions: [19],
    },
  ],
  questions: surveyQuestions,
};
